/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DoctorProfessionSpeciality } from '../../models/doctor-profession-speciality';

export interface GetDoctorProfessionSpecialityById$Params {

/**
 * ID del doctorProfessionSpeciality a recuperar.
 */
  id: number;
}

export function getDoctorProfessionSpecialityById(http: HttpClient, rootUrl: string, params: GetDoctorProfessionSpecialityById$Params, context?: HttpContext): Observable<StrictHttpResponse<DoctorProfessionSpeciality>> {
  const rb = new RequestBuilder(rootUrl, getDoctorProfessionSpecialityById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DoctorProfessionSpeciality>;
    })
  );
}

getDoctorProfessionSpecialityById.PATH = '/doctorprofessionspecialities/{id}';
