/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRegisterDto } from '../models/user-register-dto';
export interface AuthenticationResponse {
  token?: string;
  userRegister?: UserRegisterDto;
}
