/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Country } from '../models/country';

/**
 * Detalles del departamento a crear.
 */
export interface Departamento {
  country: Country;

  /**
   * Id del Departamento
   */
  id?: number;

  /**
   * Nombre del Departamento
   */
  nombre: string;

  /**
   * Poblacion del Departamento
   */
  poblacion?: number;

  /**
   * Superficie del Departamento
   */
  superficie?: number;
}
