/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalles del DepartamentoHospital a crear.
 */
export interface DepartamentoHospital {

  /**
   * Description of Department
   */
  description?: string;

  /**
   * id of Department
   */
  id?: number;

  /**
   * Name of Department
   */
  name: string;
}
