/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalles del doctorProfessionSpeciality a crear.
 */
export interface DoctorProfessionSpeciality {

  /**
   * Description of DoctorProfessionSpeciality
   */
  description?: string;

  /**
   * Id DoctorProfessionSpeciality
   */
  id?: number;

  /**
   * Name of DoctorProfessionSpeciality
   */
  name: string;
}
