/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { NurseProfessionSpeciality } from '../models/nurse-profession-speciality';

/**
 * Detalles del Nurse a crear.
 */
export interface Nurse {
  address?: Address;

  /**
   * El ano de nacimiento de la Persona
   */
  anoNacimiento?: number;

  /**
   * Apellido Materno de la Persona
   */
  apellidoMaterno?: string;

  /**
   * Apellido Paterno de la Persona
   */
  apellidoPaterno: string;

  /**
   * Celular de la Persona
   */
  celular?: string;

  /**
   * El dia de nacimiento de la Persona
   */
  diaNacimiento?: number;
  estadoCivil?: 'SOLTERO' | 'CASADO' | 'UNION_LIBRE' | 'SEPARADO' | 'DIVORCIADO' | 'VIUDO';

  /**
   * La fecha de nacimiento de la Persona
   */
  fechaNacimiento?: string;
  genero?: 'MASCULINO' | 'FEMENINO' | 'DESCONOCIDO';

  /**
   * Id de la Persona
   */
  id?: number;

  /**
   * Id Card of Nurses
   */
  idCard?: string;

  /**
   * El mes de nacimiento de la Persona
   */
  mesNacimiento?: number;

  /**
   * Nombre de la Persona
   */
  nombre: string;

  /**
   * Nombre Completo de la Persona
   */
  nombreCompleto?: string;

  /**
   * The Specialities of Nurses
   */
  nurseProfessionSpecialities?: Array<NurseProfessionSpeciality>;
  personType?: 'ADMIN' | 'DOCTOR' | 'NURSE' | 'PATIENT' | 'USER';

  /**
   * Photo of Nurses
   */
  photo?: string;

  /**
   * Segundo nombre de la Persona
   */
  segundoNombre?: string;

  /**
   * Telefono de la Persona
   */
  telefono: string;
}
