/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Detalles del NurseProfessionSpeciality a crear.
 */
export interface NurseProfessionSpeciality {

  /**
   * Description of Nurse specialitys
   */
  description?: string;

  /**
   * Id NursingSpecialty of Nurse
   */
  id?: number;

  /**
   * Name of Nurses speciality
   */
  name?: string;
}
