/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DoctorProfessionSpeciality } from '../models/doctor-profession-speciality';
export interface PageResponseDtoDoctorProfessionSpeciality {
  content?: Array<DoctorProfessionSpeciality>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageIndex?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
