/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Nurse } from '../models/nurse';
export interface PageResponseDtoNurse {
  content?: Array<Nurse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageIndex?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
