/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NurseProfessionSpeciality } from '../models/nurse-profession-speciality';
export interface PageResponseDtoNurseProfessionSpeciality {
  content?: Array<NurseProfessionSpeciality>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageIndex?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
