/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Departamento } from '../models/departamento';

/**
 * Detalles de la provincia a crear.
 */
export interface Provincia {
  departamento: Departamento;

  /**
   * ID de una Provincia
   */
  id?: number;

  /**
   * Nombre del Provincia
   */
  nombre: string;

  /**
   * Poblacion de la Provincia
   */
  poblacion?: number;

  /**
   * Superficie de la Provincia
   */
  superficie?: number;
}
