/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRegisterDto {
  avatar?: string;
  email: string;
  firstName: string;
  id?: number;
  lastName: string;
  password: string;
  personType: 'ADMIN' | 'DOCTOR' | 'NURSE' | 'PATIENT' | 'USER';
  roles?: Array<string>;
}
