/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Nurse } from '../../models/nurse';

export interface GetNurseById$Params {

/**
 * ID  Nurse a recuperar.
 */
  id: number;
}

export function getNurseById(http: HttpClient, rootUrl: string, params: GetNurseById$Params, context?: HttpContext): Observable<StrictHttpResponse<Nurse>> {
  const rb = new RequestBuilder(rootUrl, getNurseById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Nurse>;
    })
  );
}

getNurseById.PATH = '/nurses/{id}';
