/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Nurse } from '../../models/nurse';

export interface UpdateNurse$Params {

/**
 * ID del Nurse a actualizar.
 */
  id: number;
      body: Nurse
}

export function updateNurse(http: HttpClient, rootUrl: string, params: UpdateNurse$Params, context?: HttpContext): Observable<StrictHttpResponse<Nurse>> {
  const rb = new RequestBuilder(rootUrl, updateNurse.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Nurse>;
    })
  );
}

updateNurse.PATH = '/nurses/{id}';
