/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NurseProfessionSpeciality } from '../../models/nurse-profession-speciality';

export interface GetNurseProfessionSpecialityById$Params {

/**
 * ID del nurseProfessionSpeciality a recuperar.
 */
  id: number;
}

export function getNurseProfessionSpecialityById(http: HttpClient, rootUrl: string, params: GetNurseProfessionSpecialityById$Params, context?: HttpContext): Observable<StrictHttpResponse<NurseProfessionSpeciality>> {
  const rb = new RequestBuilder(rootUrl, getNurseProfessionSpecialityById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NurseProfessionSpeciality>;
    })
  );
}

getNurseProfessionSpecialityById.PATH = '/nurseprofessionspecialities/{id}';
