/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NurseProfessionSpeciality } from '../../models/nurse-profession-speciality';

export interface GetAllNurseProfessionSpecialities$Params {
}

export function getAllNurseProfessionSpecialities(http: HttpClient, rootUrl: string, params?: GetAllNurseProfessionSpecialities$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NurseProfessionSpeciality>>> {
  const rb = new RequestBuilder(rootUrl, getAllNurseProfessionSpecialities.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<NurseProfessionSpeciality>>;
    })
  );
}

getAllNurseProfessionSpecialities.PATH = '/nurseprofessionspecialities/all';
