/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NurseProfessionSpeciality } from '../../models/nurse-profession-speciality';

export interface UpdateNurseProfessionSpeciality$Params {

/**
 * ID del NurseProfessionSpeciality a actualizar.
 */
  id: number;
      body: NurseProfessionSpeciality
}

export function updateNurseProfessionSpeciality(http: HttpClient, rootUrl: string, params: UpdateNurseProfessionSpeciality$Params, context?: HttpContext): Observable<StrictHttpResponse<NurseProfessionSpeciality>> {
  const rb = new RequestBuilder(rootUrl, updateNurseProfessionSpeciality.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NurseProfessionSpeciality>;
    })
  );
}

updateNurseProfessionSpeciality.PATH = '/nurseprofessionspecialities/{id}';
