/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { ProvinciaService } from './services/provincia.service';
import { NurseService } from './services/nurse.service';
import { NurseProfessionSpecialityService } from './services/nurse-profession-speciality.service';
import { MunicipioService } from './services/municipio.service';
import { DoctorProfessionSpecialityService } from './services/doctor-profession-speciality.service';
import { DepartamentoService } from './services/departamento.service';
import { DepartamentoHospitalService } from './services/departamento-hospital.service';
import { CountryService } from './services/country.service';
import { AuthenticationService } from './services/authentication.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    ProvinciaService,
    NurseService,
    NurseProfessionSpecialityService,
    MunicipioService,
    DoctorProfessionSpecialityService,
    DepartamentoService,
    DepartamentoHospitalService,
    CountryService,
    AuthenticationService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
