/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Address } from './models/address';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { Country } from './models/country';
export type { Departamento } from './models/departamento';
export type { DepartamentoHospital } from './models/departamento-hospital';
export type { DoctorProfessionSpeciality } from './models/doctor-profession-speciality';
export type { Municipio } from './models/municipio';
export type { Nurse } from './models/nurse';
export type { NurseProfessionSpeciality } from './models/nurse-profession-speciality';
export type { PageResponseDtoCountry } from './models/page-response-dto-country';
export type { PageResponseDtoDepartamento } from './models/page-response-dto-departamento';
export type { PageResponseDtoDepartamentoHospital } from './models/page-response-dto-departamento-hospital';
export type { PageResponseDtoDoctorProfessionSpeciality } from './models/page-response-dto-doctor-profession-speciality';
export type { PageResponseDtoMunicipio } from './models/page-response-dto-municipio';
export type { PageResponseDtoNurse } from './models/page-response-dto-nurse';
export type { PageResponseDtoNurseProfessionSpeciality } from './models/page-response-dto-nurse-profession-speciality';
export type { PageResponseDtoProvincia } from './models/page-response-dto-provincia';
export type { Provincia } from './models/provincia';
export type { UserRegisterDto } from './models/user-register-dto';
