/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ProvinciaService } from './services/provincia.service';
export { NurseService } from './services/nurse.service';
export { NurseProfessionSpecialityService } from './services/nurse-profession-speciality.service';
export { MunicipioService } from './services/municipio.service';
export { DoctorProfessionSpecialityService } from './services/doctor-profession-speciality.service';
export { DepartamentoService } from './services/departamento.service';
export { DepartamentoHospitalService } from './services/departamento-hospital.service';
export { CountryService } from './services/country.service';
export { AvatarControllerService } from './services/avatar-controller.service';
export { AuthenticationService } from './services/authentication.service';
