/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DepartamentoHospital } from '../../models/departamento-hospital';

export interface GetAllDepartamentoHospital$Params {
}

export function getAllDepartamentoHospital(http: HttpClient, rootUrl: string, params?: GetAllDepartamentoHospital$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DepartamentoHospital>>> {
  const rb = new RequestBuilder(rootUrl, getAllDepartamentoHospital.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DepartamentoHospital>>;
    })
  );
}

getAllDepartamentoHospital.PATH = '/departamentohospitales/all';
